---
title: "Chess Tournament"
author: "Asher Meyers"
date: "February 16, 2016"
output: html_document
---

Load in the stringr library and the dataset TournamentInfo
```{r}
library(stringr)
TournamentInfo <- read.csv(url("https://raw.githubusercontent.com/AsherMeyers/DATA-607/master/tournamentinfo.txt"), sep = "|", stringsAsFactors=FALSE)
TournamentInfo <- TournamentInfo[seq(-2,-194,-3),]
View(TournamentInfo)
```


Separate the TournamentInfo table into two tables comprised only of each kind of row.
```{r}
NameRows <- TournamentInfo[seq(2,2*194/3,2),]
View(NameRows)
NoNameRows <- TournamentInfo[seq(3,2*194/3,2),]
View(NoNameRows)
```

Pre-Rating Location
```{r}
PreRatingLoc <- c(str_locate(NoNameRows[,2],"R: ")[1,2]+1, str_locate(NoNameRows[,2], "R: ")[1,2]+4)
PreRatings <- as.integer(str_sub(NoNameRows[,2],PreRatingLoc[1],PreRatingLoc[2]))
```

Write a table with Player’s Name, Player’s State, Total Number of Points, Player’s Pre-Rating, and Average Pre-Chess Rating of Opponent
```{r}
ChessTable <- data.frame(c(1:64), sapply(NameRows[2],str_trim),NoNameRows[1],NameRows[3], PreRatings)
colnames(ChessTable) <- c("Number", "Name", "State", "Points", "PreRating")
View(ChessTable)
```


Listing of each player's opponents
```{r}
Opponents <- data.frame(1, as.list(as.numeric(str_extract(NameRows[1,4:9],"[0-9]{1,2}"))))
colnames(Opponents) <- c("Number", "Opp1","Opp2","Opp3","Opp4","Opp5","Opp6")
for (i in 2:64) {
  Opponents <- rbind(Opponents, as.numeric(str_extract(NameRows[i,4:9],"[0-9]{1,2}")))
}
View(Opponents)
```

Opponent's Ratings Table

```{r}
OppRatings <- data.frame(c(1:64),ChessTable$PreRating[Opponents$Opp1[1:64]],ChessTable$PreRating[Opponents$Opp2[1:64]],ChessTable$PreRating[Opponents$Opp3[1:64]],ChessTable$PreRating[Opponents$Opp4[1:64]],ChessTable$PreRating[Opponents$Opp5[1:64]],ChessTable$PreRating[Opponents$Opp6[1:64]])
colnames(OppRatings) <- c("Player","Opp1R","Opp2R","Opp3R","Opp4R","Opp5R","Opp6R")
OppRatings$NullCount <- 0*seq(1:64)
for (i in 1:64) {
  OppRatings$NullCount[i] <- sum(is.na(OppRatings[i,2:7]))
  OppRatings$Average[i] <- round(sum(OppRatings[i,2:7]/(6-OppRatings$NullCount[i]), na.rm = TRUE),0)
}
View(OppRatings)
```


```{r}
ChessTable$OpponentAverage <- OppRatings$Average
View(ChessTable)
```

